### ISSUE TITLE
<3 

### ISSUE THREAD

**Issue by ahyield** [Gue3bara/Cairo#13]
😘

**Comment by AbdullZ7** [comment]
لو تستبدل شكل رقم 2 إلى نفس الشكل المستخدم في خط الرقعه .. أعتقد بيكون أفضل

**Comment by ahyield** [comment]
@AbdullZ7 يا عم افتح issue 
تانيه.
انا داخل أحب الراجل وأشكره

**Comment by davelab6** [comment]
:D

**Comment by Gue3bara** [comment]
هههههههه @ahmgeek  
صلوا ع النبي ياخونا الاشو يساع الكل :D

@AbdullZ7 
الشكل الحالي للرقم ٢ هو بالفعل الأشبه بالرقم فالرقعة انا بميل له اكتر لاني بحس انه بيكون متميز عن باقي الأرقام المشابهة في المقاس الصغير للخط كمان هو بالمناسبة نفس الرسم في النسخ والكوفي وبرأيي هو الأصح في رسم الرقم ٢ في الأرقام الهندية
لكن اعتقد انك بتقصد انك حابه يكون في الشكل المستقيم لرسمة الرقم واللي اكتر تداولا في رسمه باليد واللي هو رقم ٦ مقلوب افقيا
<img width="763" alt="screenshot 2016-06-18 00 15 44" src="https://cloud.githubusercontent.com/assets/12478169/16166225/db1eb8a6-34e9-11e6-8156-949365bb3bd2.png">
واللي شفت انه مش مميز فالقراءة في حالة خط كايرو 
لكن انا سعيد بتعليقك ودايما احب تعليقات زي دي

**Comment by ahyield** [comment]
💋 عالبركة؟، احنا نقفل الإيشو بأه
منجلكوش في حاجة وحشة يا جماعة. ميرسي لوجودكو عالكوكب، ده شيء لطيف والله.
