### ISSUE TITLE
Missing fractions and numerals

### ISSUE THREAD

**Issue by m4rc1e** [Gue3bara/Cairo#15]
Old fonts.google.com version has broken fractions and more figure sets:

![screen shot 2017-08-02 at 18 26 22](https://user-images.githubusercontent.com/7525512/28886136-44645fd2-77b0-11e7-946f-e45e7a40f191.png)

I'm guessing they were taken out because the quality was sub par?

Usually I'd like all glyphs to be included from the previous release, on this occasion I can see why you removed them.

@davelab6 what's your feeling on this one?

**Comment by davelab6** [comment]
_We can never go back_

@Gue3bara can you draw fixes?

**Comment by Gue3bara** [comment]
they were so broken 
will work on fixing and adding them back @m4rc1e @davelab6

**Comment by m4rc1e** [comment]
@Gue3bara Thank you!

**Comment by Gue3bara** [comment]
<img width="949" alt="screenshot 2017-08-03 23 56 26" src="https://user-images.githubusercontent.com/12478169/28945584-6b36049c-78a7-11e7-9efe-259470a74132.png">
added all missing numbers & fractions that existed on the older version
