### ISSUE TITLE
Kerning differences against 2.001

### ISSUE THREAD

**Issue by m4rc1e** [Gue3bara/Cairo#18]
Hey,

v2.007 has around 900 missng pairs when compared against v2.001. There are around 30 which are greater than +80/-80 units. I recommend we include them.

![cairo-kerning](https://user-images.githubusercontent.com/7525512/31603513-53197e58-b258-11e7-8329-9c5839ff5960.gif)

cc @davelab6.

Dave, do you agree on including kerns which are around 80? by having better diff tools, we're opening up pandoras box. I think we need to agree on tolerances on what is acceptable or we may never release an update again.

**Comment by m4rc1e** [comment]
Attached are the pairs.

[cairo_kerns.txt](https://github.com/Gue3bara/Cairo/files/1386779/cairo_kerns.txt)

Dave, It would be useful to write an importer for Glyphs which can do this automatically.

**Comment by Gue3bara** [comment]
This is odd i haven't messed with the kerning between the two versions 
will look into it

**Comment by m4rc1e** [comment]
@Gue3bara yeah, this could be a Glyphs issue. If you wouldn't mind looking into this, I'd be really happy.

**Comment by Gue3bara** [comment]
<img width="341" alt="screenshot 2017-10-16 13 43 15" src="https://user-images.githubusercontent.com/12478169/31610406-99fddd1e-b280-11e7-9d17-ef5fe9b0a942.png">
<img width="341" alt="screenshot 2017-10-16 13 43 28" src="https://user-images.githubusercontent.com/12478169/31610407-9a214e02-b280-11e7-8f48-c1fc8a219c3d.png">
I just checked the kerning for both versions 
v2.007 has 163 more kerning pairs than the older version 
I'm trying to understand how to solve the issue

**Comment by davelab6** [comment]
Marc, I agree you should decide tolerances and have checks for them in
fontbakery and/or diffenator :)

Please set up time with Gaber to investigate this, we need to ship these
out within 4 weeks from now :)

**Comment by davelab6** [comment]
Additionally, since this is primarily a Arabic family, I don't mind too much the kerning regression here. It is more important to get the Arabic out, because this update fixes major bugs in the Arabic.

**Comment by Gue3bara** [comment]
A new version of Cairo is now available using the masters provided from Michele and Luciano Perondi
So according to the new update the font should have the same kerning groups exactly as Titillium web
