### ISSUE TITLE
GF Review R02

### ISSUE THREAD

**Issue by m4rc1e** [Gue3bara/Cairo#20]
Glyphs:
Thorn currrently looks like this

![screen shot 2017-11-24 at 12 16 15](https://user-images.githubusercontent.com/7525512/33210294-80e19136-d111-11e7-9e3e-928c078df61e.png)

Here's a gif of the modified glyphs when compared to the fonts hosted on GF

![desktop_os_x_el_capitan_safari_9 1_](https://user-images.githubusercontent.com/7525512/33210318-9a2d812c-d111-11e7-837c-87a0841aeb0d.gif)

Also, there's quite a dramatic change in weight in the Light. The new version is much lighter. 

cc @davelab6

**Comment by Gue3bara** [comment]
<img width="843" alt="screenshot 2017-11-24 16 40 50" src="https://user-images.githubusercontent.com/12478169/33214874-4aa3b5d4-d136-11e7-9dd3-8f0b9d70c35a.png">
Fixed, 

Yet another update will be coming by mid Dec as i finally got the source files for Titillium 
so will make sure to revise the current version with the sourcefiles from the creators once again as i update Cairo with an italic version.
