### ISSUE TITLE
U+0658 ARABIC MARK NOON GHUNNA does not look right

### ISSUE THREAD

**Issue by khaledhosny** [Gue3bara/Cairo#22]
The current glyph looks like a small lam, however it should be crescent-like, compare Cairo glyph with Amiri and Noto Naskh Arabic glyphs (ignore the dotted circle):
![cairo](https://user-images.githubusercontent.com/93914/34458240-61fffcf6-edd3-11e7-8818-11e45f874d33.png) ![amiri](https://user-images.githubusercontent.com/93914/34458246-8da977e2-edd3-11e7-89a7-f878a12fea76.png) ![noto](https://user-images.githubusercontent.com/93914/34458257-e597580c-edd3-11e7-8d78-f2a0ce55feea.png)

**Comment by Gue3bara** [comment]
I built it to take the same curvature of letter noon 
will revise the design according to the reference and update you though

**Comment by Gue3bara** [comment]
<img width="326" alt="screenshot 2018-01-01 23 17 25" src="https://user-images.githubusercontent.com/12478169/34471162-faa5554c-ef49-11e7-9c85-5f71bb0c36ea.png">
I think this approach would be more suitable, don't you think?

**Comment by khaledhosny** [comment]
I’d make the horizontal lines shorter.

**Comment by Gue3bara** [comment]
@khaledhosny you mean the vertical lines of the noon like so..
<img width="396" alt="screenshot 2018-01-02 18 16 10" src="https://user-images.githubusercontent.com/12478169/34490609-0980fea0-efe9-11e7-8208-07b3e416d5e1.png">

**Comment by khaledhosny** [comment]
Yes, I think this is better (though I’m not an Urdu reader).

**Comment by Gue3bara** [comment]
This one seems close The approach in noto so i guess it's better than before
