### ISSUE TITLE
Arabic comma

### ISSUE THREAD

**Issue by heshamghaleb** [Gue3bara/Cairo#23]
Do we have a fix for Arabic comma? In this font the Arabic comma is showing as , even though it has been encoded as an ARabic comma going upwards.

<img width="277" alt="image1" src="https://user-images.githubusercontent.com/30388715/36758933-d4b7d01c-1c26-11e8-8d04-7f95e6f38652.png">

**Comment by Gue3bara** [comment]
You are using an old release of the font, can you please let me know if this is the version on GF?
because i solved this issue in the current release 
<img width="796" alt="screen shot 2018-03-02 at 3 53 08 pm" src="https://user-images.githubusercontent.com/12478169/36902206-5bb83ab8-1e32-11e8-81ef-5efa43bd6da2.png">

**Comment by heshamghaleb** [comment]
Thanks.

Can we find this latest version in google CDN? We are using a google font, isn’t this the same right?

 [cid:image001.png@01D31766.745A14C0]
Hesham Ghaleb
Accenture Middle East BV
16th Floor - Arenco Tower, Media City
P.O. Box 33283, Dubai, UAE
Mobile (UAE):     +971 55 1098200<tel:+971%C2%A055%201098200>
hesham.ghaleb@accenture.com<mailto:hesham.ghaleb@accenture.com>
www.accenture.com<http://www.accenture.com/>

On Mar 2, 2018, at 17:57, Mohamed Gaber <notifications@github.com<mailto:notifications@github.com>> wrote:


You are using an old release of the font, can you please let me know if this is the version on GF?
because i solved this issue in the current release
[screen shot 2018-03-02 at 3 53 08 pm]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_12478169_36902206-2D5bb83ab8-2D1e32-2D11e8-2D81ef-2D5efa43bd6da2.png&d=DwMFaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=qKbjpyT7b1b3RdGLeQeVtllSCVfABpmB1iaL2Ua0nR0&m=mEtWUym1-2WmEWfO1D-tnnbTAiu8WOKVHOxjzTN3Ofw&s=KQq6owTW5rnQJDH9rg8jnjUJeTw9FFLRQy5FeG6zLjU&e=>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Gue3bara_Cairo_issues_23-23issuecomment-2D369927358&d=DwMFaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=qKbjpyT7b1b3RdGLeQeVtllSCVfABpmB1iaL2Ua0nR0&m=mEtWUym1-2WmEWfO1D-tnnbTAiu8WOKVHOxjzTN3Ofw&s=kAyKA599fiNfm1GXhYTQI7mCFPRNtGY7SOArcsgYphU&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ac-2Dx62XH2O9yoHUXskbXEGQI0a8W-5FgUDks5taU-5FagaJpZM4SVwU-5F&d=DwMFaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=qKbjpyT7b1b3RdGLeQeVtllSCVfABpmB1iaL2Ua0nR0&m=mEtWUym1-2WmEWfO1D-tnnbTAiu8WOKVHOxjzTN3Ofw&s=ewCBFweGdnjGkzGqhsNckMyJEt86t3eUVR09Dg51kII&e=>.

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy.
______________________________________________________________________________________

www.accenture.com

**Comment by Gue3bara** [comment]
@davelab6 any idea when will the new release of Cairo font be pushed?
