### ISSUE TITLE
Black weight difference

### ISSUE THREAD

**Issue by m4rc1e** [Gue3bara/Cairo#28]
I know I've mentioned this before but I think this weight increase is a deal breaker atm.

![desktop_os_x_el_capitan_safari_9 1_](https://user-images.githubusercontent.com/7525512/37896964-f48638e6-30dc-11e8-8f4f-9c181867efb0.gif)

At GF, we've had a lot of complaints when we've deviated too much from previous releases.

https://github.com/google/fonts/issues/1307

cc @davelab6

**Comment by Gue3bara** [comment]
When i worked on this updated version of Cairo the main goal was to have it 100% matching with the current [Titillium Web](https://fonts.google.com/specimen/Titillium+Web) so we can merge the two families as one under the title Titillium Web 
and using the provided masters from Titillium Web creators this is the actual black weight to match 

so @davelab6 what do you advice to do

**Comment by m4rc1e** [comment]
I see! 

Thank you for the explanation.

**Comment by davelab6** [comment]
Arabic is primarily, Latin is secondary

**Comment by Gue3bara** [comment]
@davelab6 what do you advice to do?
have two versions? one with the black matching old cairo weight and one with the black matching Titillium Web?

**Comment by davelab6** [comment]
The family should be the best it can be

**Comment by m4rc1e** [comment]
Just compared this version of Cairo to the latest Titilium. Cairo's Black is now same weight as Titilium's.

If we did PR this, people will complain and our alibi is the fact it now matches the Latin counterpart.

**Comment by davelab6** [comment]
It may be that titillium is delisted due to rfn and upstream going dark

**Comment by Gue3bara** [comment]
Current version of Cairo is the best it can be
and i personally would love for it to go with the heavier weight if possible 
but also open to all suggestions

**Comment by davelab6** [comment]
Yeah let's do it then but be sure to explain why in the PR and tweet out
the PR link in English and Arabic to warn people

**Comment by Gue3bara** [comment]
I will be promoting about the new release heavily anyway so will totally do 
i believe the new release is way better than the older one and people need to know that

**Comment by Gue3bara** [comment]
I'm closing this issue now as the weight difference issue is solved in the new build
