### ISSUE TITLE
Adding Vietnamese

### ISSUE THREAD

**Issue by crystaltype** [Gue3bara/Cairo#29]
Hi,

I see that this type doesn't have Vietnamese yet.

I'm willing to contribute the complete Vietnamese character set directly, by sending you a 'vietnamese only' glyphapp file for you to review and integrate (Or make changes myself and make a pull request from my fork.)

Or, you can make changes and then push your work to master and I will give further feedback :)

Please respond ASAP. Thanks!

P/S: I'm a Vietnamese native speaker and a self-study graphic designer/type designer. I have been working with fonts for over 5 years! I'm here to (hopefully) make google fonts a better place for people using Vietnamese! :) Thanks!

cc': @davelab6

**Comment by Gue3bara** [comment]
Hello @crystaltype 
Thank you so much for your intrest in adding further support to the font family 
you can share with me the vietnamese only masters and i will review and integrate then we can review and see if any fixes are needed

**Comment by crystaltype** [comment]
Thank you!
So what's your email address? I'll begin working at it as soon as possible, and will send you an email when I'm done.

**Comment by Gue3bara** [comment]
you can contact me on gaber(at)gaberism(dot)net
