### ISSUE TITLE
Arabic mark redesign preview

### ISSUE THREAD

**Issue by m4rc1e** [Gue3bara/Cairo#33]
Hey @Gue3bara 

This isn't an issue, I thought I'd just demo the new abilities of our regressions tools.

Soon GFR will be able to check regressions in kerning, marks and mkmks. Here's a preview or Cairo's new marks.

![desktop_windows_7_ie_9 0_](https://user-images.githubusercontent.com/7525512/42517684-3569462c-8458-11e8-9795-43ccb05ff4ac.gif)

cc @davelab6

**Comment by Gue3bara** [comment]
all marks are updated and reviewed in the new build
