### ISSUE TITLE
Arabic characters appears spaced

### ISSUE THREAD

**Issue by h3t1** [Gue3bara/Cairo#36]
### Arabic characters appears spaced!
![image](https://user-images.githubusercontent.com/20133892/55949648-ffc5d000-5c4a-11e9-8f15-81234d3561a8.png)

_tested on : Xperia Sp CyanogenMod / Android 4.4.4 / Default browser: version 4.4.4-ee3ac4920f_

**Comment by h3t1** [comment]
Alright, I figured out how to fix this issue.
this behavior is caused by the fact that this browser does not support the woff2 format, which is the only format imported by Google fonts.

**Comment by Gue3bara** [comment]
> Alright, I figured out how to fix this issue.
> this behavior is caused by the fact that this browser does not support the woff2 format, which is the only format imported by Google fonts.

That and the fact that this is not Cairo font, its droid kufi :)

**Comment by houssamala** [comment]
شكرا على المجموعة الرائعة منك اخ جابر
خط كايرو فعلا قوي جدا نتمنى اضافة يكون(ح) قريب من droid وشكرا جدا ليك
ونتمنى انشوف جديدك
