### ISSUE TITLE
hehgoal-ar.medi - Outline overlap is causing rendering issues

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#38]
I suggest removing the outer overlap. The test render is from the automatically generated Google Fonts QA images found here: https://github.com/google/fonts/pull/2380#issuecomment-596303830

![drawing issues](https://user-images.githubusercontent.com/5162664/76363667-ebc29c80-62f9-11ea-99ac-36febafde073.png)
QA image:
![QA render](https://user-images.githubusercontent.com/5162664/76363684-f2e9aa80-62f9-11ea-9e48-f6e709849f9a.png)

**Comment by Gue3bara** [comment]
Noted and fixed all outline overlaps and [exterior overlaps](https://groups.google.com/forum/m/#!topic/googlefonts-discuss/GFeqmTWKez8)
