### ISSUE TITLE
tcheh-ar - Drawing has issues at heavier weights

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#39]
Glyphs source:
![Screen Shot 2020-03-11 at 11 25 26 AM](https://user-images.githubusercontent.com/5162664/76435697-b7002500-638d-11ea-981a-95741c677372.png)

QA Images from: https://github.com/google/fonts/pull/2380#issuecomment-596303830
![Screen Shot 2020-03-11 at 11 46 02 AM](https://user-images.githubusercontent.com/5162664/76435971-0d6d6380-638e-11ea-9003-b628c88dfdd9.png)

**Comment by Gue3bara** [comment]
I'm using a hah alternative to illustrate the tcheh 
<img width="1792" alt="Screenshot 2020-03-12 01 26 55" src="https://user-images.githubusercontent.com/12478169/76493410-97eeab00-6400-11ea-8672-529fd0e90475.png">

it's weird that this is how it was built in the 1st place

**Comment by eliheuer** [comment]
I just looked at this in commit: https://github.com/Gue3bara/Cairo/commit/a5424a6754e3eb93e61fe337d4a047aea8b83940, looks much better. As far as I can tell this issue is fixed. Thanks!
