### ISSUE TITLE
madda-ar - Outline overlap is causing rendering issues

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#40]
![madda-ar](https://user-images.githubusercontent.com/5162664/76460660-ca72b680-63b4-11ea-8891-af242058d49e.png)

FontGoggles test from: https://github.com/google/fonts/pull/2380#issuecomment-596303830
![madda-ar-2](https://user-images.githubusercontent.com/5162664/76460666-ccd51080-63b4-11ea-9bda-1bff51262a41.png)

**Comment by Gue3bara** [comment]
fixed the overlap issues
