### ISSUE TITLE
quotesinglbase - Middle master has interpolation issues

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#41]
It looks like the `comma` component is oriented differently in the Black and ExtraLight masters, and too small in the Regular master.

Note the interpolation preview at the bottom of this screenshot, from the following commit: https://github.com/google/fonts/pull/2380#issuecomment-596303830
![quotesinglbase-1](https://user-images.githubusercontent.com/5162664/76464657-1d03a100-63bc-11ea-9c2b-526cda212096.png)

**Comment by Gue3bara** [comment]
issue was solved the last master component was upside down  
<img width="1792" alt="Screenshot 2020-03-12 01 32 11" src="https://user-images.githubusercontent.com/12478169/76493728-527ead80-6401-11ea-9a79-a217d544c476.png">
