### ISSUE TITLE
percent-ar - Outlines are in the wrong order, causing interpolation issues.

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#42]
See the screenshot below taken from commit: https://github.com/Gue3bara/Cairo/commit/b9ce6f9df6454e167817e30695d32809181b7913

![ERucUSnN](https://user-images.githubusercontent.com/5162664/76495622-9ecfea80-640d-11ea-95a4-b6a95c0c6b8b.png)

**Comment by Gue3bara** [comment]
I solved this issue now, but I did before and for some reason it keeps reoccurring.

**Comment by Gue3bara** [comment]
@eliheuer but we can mark it as solved for now 
<img width="1577" alt="Screenshot 2020-03-15 19 14 32" src="https://user-images.githubusercontent.com/12478169/76706602-3a54aa00-66f1-11ea-9e4b-5c949b82b489.png">
