### ISSUE TITLE
dollar [U+0024] - Use bracket layers and fix point order to avoid outline issues

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#43]
Below is a gif showing an animation of the dollar glyph from two variable fonts interpolating. Kreon on the left and Cairo(at commit b563b7324315b253210eec761bc4873f5d0b5131) on the right. Note how Cairo twists and becomes distorted due to non-matching point order. Also note how Kreon jumps between two drawing styles, this is done with bracket layers.

![dollar](https://user-images.githubusercontent.com/5162664/76787655-dfbe5b00-678f-11ea-945b-c173c1b3787f.gif)

There is a tutorial showing how to set up bracket layers here:
https://glyphsapp.com/tutorials/alternating-glyph-shapes

I will attempt a PR adding/fixing this if this issue stays open more than a few days.

**Comment by Gue3bara** [comment]
![Kapture 2020-03-16 at 23 06 13](https://user-images.githubusercontent.com/12478169/76799729-c5f63580-67da-11ea-92fc-d2e8df27d6ab.gif)
Thank you @eliheuer  for the tip
