### ISSUE TITLE
Oslash [U+00D8] - Use bracket layers and fix point order to avoid outline issues

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#44]
This is similar to issue #43, see the screenshot below from the glyphs source at commit b563b7324315b253210eec761bc4873f5d0b5131

![Oslash](https://user-images.githubusercontent.com/5162664/76791981-60815500-6798-11ea-8430-0fd5dbcdff85.png)

**Comment by Gue3bara** [comment]
<img width="882" alt="Screenshot 2020-03-16 22 21 14" src="https://user-images.githubusercontent.com/12478169/76796592-744aac80-67d4-11ea-8fe1-5a79805e17a7.png">
I spent today working on reviewing all interpolation issues in the latin and the arabic this and many others i noticed them and worked on them 
will push the new build tonight

**Comment by Gue3bara** [comment]
<img width="862" alt="Screenshot 2020-03-16 23 14 38" src="https://user-images.githubusercontent.com/12478169/76800246-ebd00a00-67db-11ea-9369-6b1167e2cc14.png">
Much better now
@eliheuer
