### ISSUE TITLE
multiply [U+00D7] - Outline point order causing interpolation issues.

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#45]
The point order in the Black weight is different from the Regular and ExtraLight in the source file at commit b563b7324315b253210eec761bc4873f5d0b5131, causing interpolation issues, see below.

![multiply](https://user-images.githubusercontent.com/5162664/76792891-5e1ffa80-679a-11ea-907e-5276a1efbc11.png)

**Comment by Gue3bara** [comment]
<img width="743" alt="Screenshot 2020-03-16 22 19 37" src="https://user-images.githubusercontent.com/12478169/76796494-3c436980-67d4-11ea-9426-bbe7da84b3d8.png">

noted and solved
