### ISSUE TITLE
oslash [U+00F8] - Use bracket layers to avoid outline issues

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#46]
This is similar to issue #43, see the screenshot below from the glyphs source at commit b563b7324315b253210eec761bc4873f5d0b5131

![oslash](https://user-images.githubusercontent.com/5162664/76793157-eb634f00-679a-11ea-982a-7a81aa485f26.png)

**Comment by Gue3bara** [comment]
<img width="860" alt="Screenshot 2020-03-16 22 18 33" src="https://user-images.githubusercontent.com/12478169/76796444-1c13aa80-67d4-11ea-9b5d-eea5529b8973.png">
noted and solved in the latest build i will push tonight

**Comment by Gue3bara** [comment]
<img width="729" alt="Screenshot 2020-03-16 23 11 32" src="https://user-images.githubusercontent.com/12478169/76800110-9b58ac80-67db-11ea-815d-1cb1c2b96c35.png">
Now re did it using the bracket layer and its much better 
thank you @eliheuer
