### ISSUE TITLE
Oslash and oslash - extra layers crash fontmake build script

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#48]
I removed the circled layers from the screenshot below in commit 3719d6f573c2e3c7fbdcf2ad155b4646c73a5ac7 and that seems to have fixed the problem, a PR with my fixes is here: https://github.com/Gue3bara/Cairo/pull/47

Feel free to not merge and close the PR if it's easier to fix this yourself. 

![oslash](https://user-images.githubusercontent.com/5162664/76821563-a95efb00-67e4-11ea-9fc5-d88fd0769aaf.png)

![oslash-crash](https://user-images.githubusercontent.com/5162664/76821566-acf28200-67e4-11ea-934b-3dba707d57b7.png)

**Comment by Gue3bara** [comment]
I merged your request and it's all good now
