### ISSUE TITLE
dollar -  extra layers crash fontmake build script

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#49]
I removed the circled layer from the screenshot below in commit 3719d6f573c2e3c7fbdcf2ad155b4646c73a5ac7 and that seems to have fixed the problem, a PR with my fixes is here: https://github.com/Gue3bara/Cairo/pull/47

Feel free to not merge and close the PR if it's easier to fix this yourself.

![dollar](https://user-images.githubusercontent.com/5162664/76821866-9a2c7d00-67e5-11ea-8ecc-60be5130fb28.png)

![dollar-crash](https://user-images.githubusercontent.com/5162664/76821873-9c8ed700-67e5-11ea-8dd3-238869c6cfa1.png)

**Comment by Gue3bara** [comment]
Thank you so much @eliheuer 
I merged and its all good now
