### ISSUE TITLE
New Heavy weight from commit 4f917cb  causing weight coordinates issues in QA

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#50]
The new Heavy weight  from commit 4f917cb is causing some Fontbakery QA fails, see the report [here](https://github.com/google/fonts/pull/2380#issuecomment-599874297) and below.

## Fontbakery report

Fontbakery version: 0.7.20

<summary><b>[4] Cairo[wght].ttf</b></summary>
<summary>🔥 <b>FAIL:</b> Variable font weight coordinates must be multiples of 100.</summary>

* [com.google.fonts/check/varfont_weight_instances](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont_weight_instances)
<pre>--- Rationale ---

The named instances on the weight axis of a variable font must have coordinates
that are multiples of 100 on the design space.

</pre>

* 🔥 **FAIL** Found a variable font instance with 'wght'=785.10638. This should instead be a multiple of 100. [code: bad-coordinate]

<summary>🔥 <b>FAIL:</b> Check variable font instances have correct coordinate values</summary>

* [com.google.fonts/check/varfont_instance_coordinates](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont_instance_coordinates)

* 🔥 **FAIL** Instance "Black" wght value is "785.10638". It should be "900.0" [code: bad-coordinate]
* 🔥 **FAIL** Instance "Heavy" wght value is "900.0". It should be "400.0" [code: bad-coordinate]

<summary>🔥 <b>FAIL:</b> Check variable font instances have correct names</summary>

* [com.google.fonts/check/varfont_instance_names](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont_instance_names)

* 🔥 **FAIL** Instance name "Heavy" is incorrect. It should be "" [code: bad-name]
* 🔥 **FAIL** This will cause problems with some of the Google Fonts systems that look up fonts by their style names. This must be fixed! [code: bad-instance-names]

</pre>

<br>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 4 | 3 | 36 | 9 | 114 | 0 |
| 0% | 2% | 2% | 22% | 5% | 69% | 0% |

**Note:** The following loglevels were omitted in this report:
* **WARN**
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**

**Comment by eliheuer** [comment]
I'm experimenting with ways to fix this now, will report back with what I find. The main issue is that Black and Heavy are both set to 900 in the instance field.

![heavy](https://user-images.githubusercontent.com/5162664/76871168-1bfdc400-6841-11ea-8b3e-2ba1f3ee9433.png)

**Comment by Gue3bara** [comment]
@eliheuer I noticed the issue as I was doing the comparison between the old and new Black 
i noticed that it's not being recognized and still compared to the "heavy" weight 
this seems like a Glyphs limitation, I wonder if it can be solved used a custom parameter 
i will try that out and report it on Glyphs form to ask for help

**Comment by Gue3bara** [comment]
@eliheuer i just added the custom parameter for the weight class 
i think this should work

**Comment by eliheuer** [comment]
Nice I was doing the same. Thanks. I think dave said he wanted the heavy to be 1000, but I've never worked on a font that goes beyond 900, so I'm not completely sure what the best way to do this is.

Edit: I see the new source, trying it now, thanks.

**Comment by Gue3bara** [comment]
@eliheuer I just pushed a new build 
there was an interpolation issue with the $ Oslash & oslasg that might have caused the issue, 
i think we should give the new build a try

**Comment by eliheuer** [comment]
Sorry for the lack of progress, the new builds are crashing the QA tools, I think it might be due to the new heavy weight. So it's a problem with the GF QA tools, not the new source files.

**Comment by eliheuer** [comment]
I talked with Marc today, and the QA tools need an update before they can handle a 1000 Heavy weight, I made an issue about this here here: https://github.com/googlefonts/gfregression/issues/61

**Comment by eliheuer** [comment]
Marc said this will be fixed tomorrow, closing it now, will reopen if something goes wrong with that.
