### ISSUE TITLE
Change Heavy 1000 weight name to ExtraBlack

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#55]
Good news, the [tools on the GF end to work with 1000 weights](https://github.com/googlefonts/gfregression/pull/62#event-3163798569) work now, but the name needed for 1000 weights needs to be `ExtraBlack`. 

If the name `Heavy` is important for any reason, please ignore this issue and I can update it before building new fonts in my fork. 

As far as I can tell, only two changes are needed, one in the masters tab, and another in the instances tab. See the screenshots below:

![masters](https://user-images.githubusercontent.com/5162664/77569117-0ec78180-6ea0-11ea-8e7c-6a0babf2469e.png)

![instances](https://user-images.githubusercontent.com/5162664/77569125-1129db80-6ea0-11ea-99a2-2e2a419a39e9.png)

**Comment by Gue3bara** [comment]
@eliheuer I just fixed the issue updating the name as requested all updated it in the bracket layers so we avoid any interpolation issues
