### ISSUE TITLE
Oslash bracket layer issues

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#57]
Marc brought up some issues with the Oslash glyphs in the Pr here: https://github.com/google/fonts/pull/2380#issuecomment-606515845

Oslash bracket is working fine.
<img width="71" alt="os-1" src="https://user-images.githubusercontent.com/5162664/78041363-94cf4680-733e-11ea-8459-d830efbb5eaf.png">

It isn't working for accented Oslash glyphs.
<img width="107" alt="os-2" src="https://user-images.githubusercontent.com/5162664/78041442-b3354200-733e-11ea-888d-983505c56b5f.png">

Should the Oslash even be bracketed? Will it lead to confusion?

**Comment by eliheuer** [comment]
In the variable font, between 900 and 1000, there are some visual issues as well.

![oslash](https://user-images.githubusercontent.com/5162664/78042232-bd0b7500-733f-11ea-99f2-678c97ed19a5.png)

**Comment by eliheuer** [comment]
I'm also looking at other typefaces with Black and Extra Black weights and I'm not seeing much precedent for removing the slash from the counter, most designs make the slash very thin.

**Comment by Gue3bara** [comment]
> king at other typefaces with Black and Extra Black weights and I'm not seeing much precedent for removing the slash from the counter,

@eliheuer for this case, I was following the original design when I worked on the improvement of the Latin

**Comment by eliheuer** [comment]
Ah, got it, thanks. I did find a few other designs that do this, so let's just do whatever is easy for you, but probably sticking with the original design is best?

**Comment by Gue3bara** [comment]
> her designs that do this, so let's just do what

I think let's stick to the original design and the brackets solution should've solved the issue but I will check what happened with the glyphs using the same component

**Comment by Gue3bara** [comment]
> Ah, got it, thanks. I did find a few other designs that do this, so let's just do whatever is easy for you, but probably sticking with the original design is best?

its a very confusing compatibility issue with Oslash I am still working on it

**Comment by eliheuer** [comment]
Thanks, I had to add some bracket layers last time I built the fonts. I was still having this issue with commit f264108.

![slash](https://user-images.githubusercontent.com/5162664/78203157-3603ed00-7464-11ea-9b02-dffc8d07fe79.png)

I'm doing another build now, and trying to add bracket layers to the Ǿ.
![Ǿ](https://user-images.githubusercontent.com/5162664/78204584-e1627100-7467-11ea-86fd-f7b184802661.png)

**Comment by Gue3bara** [comment]
> Thanks, I had to add some bracket layers last time I built the fonts. I was still having this issue with commit [f264108](https://github.com/Gue3bara/Cairo/commit/f264108354ff1f86a660581fe8711cd1f7509575).
> 
> ![slash](https://user-images.githubusercontent.com/5162664/78203157-3603ed00-7464-11ea-9b02-dffc8d07fe79.png)
> 
> I'm doing another build now, and trying to add bracket layers to the Ǿ.
> ![Ǿ](https://user-images.githubusercontent.com/5162664/78204584-e1627100-7467-11ea-86fd-f7b184802661.png)

@eliheuer 
I added bracket layers and still having the same issue but I think I figured it out will update you shortly

**Comment by Gue3bara** [comment]
![Kapture 2020-04-02 at 14 33 00](https://user-images.githubusercontent.com/12478169/78249646-ff26e900-74ee-11ea-9e13-ce27c494ae36.gif)
solved

**Comment by eliheuer** [comment]
Looks good, your fix is the same as the one I tried last night. I'm closing this. Thanks!
