### ISSUE TITLE
U+06BA and U+06C2 should be dual-joining

### ISSUE THREAD

**Issue by dscorbett** [Gue3bara/Cairo#59]
U+06BA ARABIC LETTER NOON GHUNNA and U+06C2 ARABIC LETTER HEH GOAL WITH HAMZA ABOVE are dual-joining, but in this font they only have isolated and final forms.
![ـںـۂـ](https://user-images.githubusercontent.com/1124347/79245470-24e4b400-7e46-11ea-8774-361c7f8dd21f.png)

**Comment by Gue3bara** [comment]
@dscorbett 
<img width="521" alt="Screenshot 2020-05-06 15 19 46" src="https://user-images.githubusercontent.com/12478169/81181635-07ba8580-8fad-11ea-81f9-327af6a961fe.png">
they are joining in my testing

**Comment by dscorbett** [comment]
I am testing [version 3.114](https://github.com/Gue3bara/Cairo/releases/tag/v3.114) with the string <U+0640, U+06BA, U+0640, U+06C2, U+0640> ⟨ـںـۂـ⟩. Maybe it was fixed since the release. Could you try testing that string?

**Comment by Gue3bara** [comment]
@dscorbett I now see the issue will try to figure it out might be a features issue

**Comment by Gue3bara** [comment]
@dscorbett the glyphs were missing
i solved it now and will push a new release 
<img width="650" alt="Screenshot 2020-05-07 18 55 28" src="https://user-images.githubusercontent.com/12478169/81322517-6870bd80-9094-11ea-8415-5cca6119fc00.png">
