### ISSUE TITLE
Add description to README.md

### ISSUE THREAD

**Issue by davelab6** [Gue3bara/Cairo#6]
Please add a few paragraphs of description about the design to the README :)

**Comment by Gue3bara** [comment]
Im on it

**Comment by davelab6** [comment]
@Gue3bara ping

**Comment by Gue3bara** [comment]
i didnt forget

**Comment by davelab6** [comment]
@Gue3bara ping :)

**Comment by davelab6** [comment]
ping :)

**Comment by Gue3bara** [comment]
on it 
and will updated today

**Comment by Gue3bara** [comment]
updated 
please check it out and later tonight will pimp out some sample jpgs :) and work on the page

**Comment by davelab6** [comment]
Nice. Merge #10 to close this issue :)

**Comment by davelab6** [comment]
Also if you visit the top of https://github.com/Gue3bara/Cairo/ you can edit the short description from

<img width="634" alt="screen shot 2016-03-15 at 15 41 08" src="https://cloud.githubusercontent.com/assets/261579/13791606/5cd38a0e-eac4-11e5-8508-8edb015229c7.png">

to 

`Arabic Font Family based on Titillium Web`
