### ISSUE TITLE
Wrong glyph for U+06D4 ARABIC FULL STOP

### ISSUE THREAD

**Issue by dscorbett** [Gue3bara/Cairo#60]
U+06D4 ARABIC FULL STOP is meant to be a baseline bar, as used in Nastaliq for the full stop. It shouldn’t look like U+002E FULL STOP.
![۔](https://user-images.githubusercontent.com/1124347/80019831-1df11d80-84a6-11ea-8642-55b058377e83.png)

**Comment by Gue3bara** [comment]
@dscorbett i dont see the issue, 
The Arabic period in contemporary typefaces comes in various shapes 
I don't see a problem with the current period for a contemporary typefaces

**Comment by dscorbett** [comment]
The issue is that a contemporary Arabic period that looks like a dot is U+002E, not U+06D4.

**Comment by Gue3bara** [comment]
@dscorbett i will check on this and get back to you

**Comment by Gue3bara** [comment]
thank you @dscorbett it's now solved and i will publish a new release including other fixes today 
<img width="1118" alt="Screenshot 2020-05-07 17 39 05" src="https://user-images.githubusercontent.com/12478169/81314687-b633f880-9089-11ea-9903-d9851b19a54c.png">
