### ISSUE TITLE
Initial U+06C1 overlaps marks below

### ISSUE THREAD

**Issue by dscorbett** [Gue3bara/Cairo#61]
The initial form of U+06C1 ARABIC LETTER HEH GOAL overlaps marks below. Here is <U+06C1 ARABIC LETTER HEH GOAL, U+0650 ARABIC KASRA, U+0640 ARABIC TATWEEL>:
![ہِـ](https://user-images.githubusercontent.com/1124347/80245582-f8484d80-8638-11ea-87ef-e785bb2e860d.png)

**Comment by Gue3bara** [comment]
Thank you so much @dscorbett 
it was mark anchor points placement and will be fixed in the next release 
<img width="366" alt="Screenshot 2020-05-06 15 15 50" src="https://user-images.githubusercontent.com/12478169/81181279-8105a880-8fac-11ea-921b-e383fa8c673b.png">
