### ISSUE TITLE
Final U+0686 Arabic Letter Tcheh ( چ ) -- Outline overlap in variable font

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#62]
Using the latest variable font built with Fontmake from this pull request(0f343df): https://github.com/google/fonts/pull/2380

I noticed that the Final Tcheh has some rendering issues due to outline overlap:
![tcheh](https://user-images.githubusercontent.com/5162664/81135590-cbdcdd00-8f26-11ea-86a8-fe62c28b4513.png)

**Comment by Gue3bara** [comment]
@eliheuer 
I checked on it and this is a preview within glyphs preview plugin 
![Kapture 2020-05-06 at 14 58 13](https://user-images.githubusercontent.com/12478169/81179690-4c90ed00-8faa-11ea-9132-6e07ac85e5ad.gif)
I'm not sure what would cause this weird behavior everything seems in place on Glyphs

**Comment by Gue3bara** [comment]
@eliheuer I figured it 
I had to decompose the dots and somehow that fixed it 
![Kapture 2020-05-07 at 17 28 46](https://user-images.githubusercontent.com/12478169/81313629-686ac080-9088-11ea-9d73-2509c799cebc.gif)

Glyphs is so broken in my Opinion

**Comment by eliheuer** [comment]
Thanks!, yeah I looked at this again today and noticed that final and isolated were both having similar but different issues.
![0608](https://user-images.githubusercontent.com/5162664/81367269-bbf60200-90ba-11ea-9753-2313761f4721.png)

Decomposing the dots works for now! Thanks again.

**Comment by Gue3bara** [comment]
> ooked at this again today and noticed that final and isolated were both having similar but different

@eliheuer that's what i tried and it works fine now 
and i pushed a new version after amending all the edits
