### ISSUE TITLE
U+201C Left Double Quotation Mark -- Outlines swap order between ExtraLight and ExtraBlack masters

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#63]
Note that the outlines swap order between ExtraLight and ExtraBlack masters:
![quote-issue](https://user-images.githubusercontent.com/5162664/81249852-aebf1180-8fed-11ea-9dcb-70bfa9270726.png)
The causes overlap that can make this glyphs look like a single quote in some weights:
![Kapture-2020-05-06-quote](https://user-images.githubusercontent.com/5162664/81249912-cd250d00-8fed-11ea-8d04-df26d98da70b.gif)

**Comment by Gue3bara** [comment]
Thank @eliheuer the compatibility issue is fixed and will push it the coming update

**Comment by Gue3bara** [comment]
![Kapture 2020-05-07 at 17 18 02](https://user-images.githubusercontent.com/12478169/81312267-bd0d3c00-9086-11ea-833d-ac5eb5c4d54e.gif)
