### ISSUE TITLE
U+FDF2 -- Add shadda and dagger alif above second lam?

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#64]
Older versions of Cairo have a shadda and dagger alif above second lam for U+FDF2.
![ufdf2](https://user-images.githubusercontent.com/5162664/81252894-29d7f600-8ff5-11ea-8751-5410beeaaf8c.gif)
Adding these back would help maintain consistency between versions, but if there is any good reason to remove them please close this issue and ignore this suggestion.

**Comment by Gue3bara** [comment]
in the new version i have two versions for the "Allah" ligature 
<img width="670" alt="Screenshot 2020-05-07 17 14 47" src="https://user-images.githubusercontent.com/12478169/81311907-44a67b00-9086-11ea-8f56-3f0955ae6936.png">
this will allow the font to write more complicated quranic version if needed while also having the simple الله form with the shadda and mad 
so it's an improvement
