### ISSUE TITLE
hungarumlaut.cap — Path order mismatch

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#65]
From the source in commit 15114e6:

The path order in the ExtraBlack master is off by one causing interpolation issues.

<img width="655" alt="hungarumlaut cap" src="https://user-images.githubusercontent.com/5162664/81976242-3f9d7a80-95f6-11ea-9cd3-7c1aa30912ac.png">

**Comment by Gue3bara** [comment]
@eliheuer i am working on it 
it's a very weird incompatibility issue that keeps reoccurring 
one of many Glyphs issues i assume

**Comment by Gue3bara** [comment]
@eliheuer I've treid everything possible to fix this issue and checked on Glyphs forum to find help but non of what i found worked 
I posted on the [forum](https://forum.glyphsapp.com/t/path-order-problem/14771) to look for a solution

**Comment by Gue3bara** [comment]
I solved the issue now
