### ISSUE TITLE
tah-ar.medi — Baseline extension has a gap

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#66]
From the source at commit 15114e6:

<img width="751" alt="tah-ar medi-1" src="https://user-images.githubusercontent.com/5162664/82005715-100d6300-9634-11ea-8f99-d022cfc78e91.png">

<img width="470" alt="tah-ar medi-2" src="https://user-images.githubusercontent.com/5162664/82005726-14d21700-9634-11ea-8bf7-6d77ca6410ed.png">

**Comment by Gue3bara** [comment]
the issue is now solved and i pushed a new version
