### ISSUE TITLE
U+F6BE — Missing private use area code point

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#67]
This might not be a serious issue, if there is any reasonable rationale for removing this code point, please ignore this issue and close it.

Previous versions of Cairo had a private use area code point U+F6BE but in newer versions it is missing. I'm not sure exactly what this glyph is used for, but it looks like it might be an alternate Reh ( ر | U+0631 )?

If someone is using this code point and gets a font update it would switch to a missing glyph box ▯.

<img width="397" alt="F6BE" src="https://user-images.githubusercontent.com/5162664/82240227-0d4a9080-9908-11ea-963b-afeb9ac86a74.png">

**Comment by Gue3bara** [comment]
@eliheuer I dont think its an alternative reh mostly something else that when i reworked titillium web i mostly removed it because it was not supported in the version i received from the designers 

what do you recommend in this case? i can just add it to the new version to avoid the issue

**Comment by eliheuer** [comment]
I think adding it back would be a good idea and avoid any possible issues, but if there is ever a good reason to remove it that should be fine also.

If anyone in the future has a problem with this code point in Cairo they can find this issue and understand what happened.

**Comment by Gue3bara** [comment]
@eliheuer I decided to add it back to better have it supported than risk causing a missing glyph issue to anyone already using it on the web
