### ISSUE TITLE
ØøǾǿ — Suggestion for a new approach to outline construction

### ISSUE THREAD

**Issue by eliheuer** [Gue3bara/Cairo#68]
Ø, ø, Ǿ, ǿ (U+00D8, U+00F8, U+01FE, U+01FF) Still have some rendering issues, the bellow examples are from the [QA images here](https://github.com/google/fonts/pull/2380#issuecomment-626063631), left is the old version and right is the new variable font, specifically Safari on macOS.

<img width="419" alt="Ø" src="https://user-images.githubusercontent.com/5162664/82271444-ca0f1280-9945-11ea-8ba8-44bea858bb3d.png">

<img width="451" alt="Øø" src="https://user-images.githubusercontent.com/5162664/82271462-d1362080-9945-11ea-936a-8dd7c53e3d55.png">

<img width="1029" alt="Ǿǿ" src="https://user-images.githubusercontent.com/5162664/82271466-d5623e00-9945-11ea-8c32-34480fc7f69e.png">

I think the cause of problems like this might be the way the outlines are constructed, for example the two overlapping outline seen here that form one diagonal slash shape.

<img width="463" alt="cairo-overlapping-shapes" src="https://user-images.githubusercontent.com/5162664/82272482-bf09b180-9948-11ea-864e-5e546f69ef4a.png">

There is another variable font built from Glyphs source that uses bracket layers for the same purpose on the same glyphs, but approaches the problem slightly differently. I'm suggesting that the four problem glyphs (Ø, ø, Ǿ, ǿ) could be updated to implement bracket layers the same way this other font has implemented them:

https://fonts.google.com/specimen/Hepta+Slab?preview.text=%C3%98%C3%B8%C7%BE%C7%BF&preview.text_type=custom

https://github.com/mjlagattuta/Hepta-Slab

https://forum.glyphsapp.com/t/multidimensional-bracket-layers/9593

**Comment by Gue3bara** [comment]
@eliheuer 
Thank you so much for the great efforts you invest in the support I greatly appreciate it really. 
I will check out how it was done for Hepta Slab it's good to learn better ways to solving this issue 
keep me updated when you have it done

**Comment by Gue3bara** [comment]
ok now I think i get it 

you don't have to make the shapes compatible between the bracket layers and the "original" layer
i thought they have to be the same count of shapes this is why i had the two overlapping outlines

**Comment by Gue3bara** [comment]
also, Hepta Slab is a really beautiful font 
i would definitely love to add Arabic support making a kufi slab font would be fun

**Comment by eliheuer** [comment]
Ok, I have a PR that should fix this. It's not ideal, but it should help move things forward.

https://github.com/Gue3bara/Cairo/pull/69

**Comment by Gue3bara** [comment]
Thank you @eliheuer  so much for the great help and support
