### ISSUE TITLE
line spacing 

### ISSUE THREAD

**Issue by FADIBRANDS** [Gue3bara/Cairo#70]
when using cairo font on word and excel it is giving a lot of line spacing that is not necessary. i managed to manually fix this issue on word by reducing line spacing from word settings. however when using Excel this feature doesn't exist. perhaps a narrow version of the font would fix the issue or fixing the hight of the the font.
![Screen Shot 2020-09-24 at 12 02 15 PM](https://user-images.githubusercontent.com/71815840/94117888-d9571d00-fe5d-11ea-9c77-cf80902e9281.png)

**Comment by Gue3bara** [comment]
@FADIBRANDS this issue is fixed in the most recent release which is not yet available on Google's platform but will be very soon

**Comment by ghost** [comment]
it still exists
