### ISSUE TITLE
Please clarify the status of this project ...

### ISSUE THREAD

**Issue by soc** [Gue3bara/Cairo#72]
... and its relationship to https://github.com/eliheuer/titillium-web-vf, which says:

> It started as a fork of Cario by Mohamed Gaber, which is a fork of Titillium Web that adds support for the Arabic Script.

The last commit in that repository was in March 2020, and its main author seems to contribute to your project now, which seems way more active. Though the fonts shipped through Google are called Titillium, not Cairo, and I'm not sure on which sources they are built.

Would it be possible for you (@Gue3bara and @eliheuer) to clear this up a bit, maybe add a sentence to the README so that it's easier to understand what purpose each repository serves?

Thanks a lot,

Simon

**Comment by Gue3bara** [comment]
The latest and most updated version of Cairo is on Cairo's rep

**Comment by soc** [comment]
Apologies for asking, didn't know there was bad blood.

**Comment by Gue3bara** [comment]
> Apologies for asking, didn't know there was bad blood.

badblood?
this project wouldn't be at this stage of it's development without @eliheuer 's contributions, help and support 
you asked a question you got the clarification!
