### ISSUE TITLE
Cairo Color

### ISSUE THREAD

**Issue by Gue3bara** [Gue3bara/Cairo#77]
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/12478169/165501255-2ffc4c1c-5807-4242-b831-efee9b910e04.png)
Hello @yanone
I saw this issue reported by Dave a while ago and I worked on pushing the updated version please check it out now

**Comment by yanone** [comment]
How did you generate the color VF in the repo? I can't reproduce it. In Glyphs directly?

**Comment by Gue3bara** [comment]
I created it using Glyphs directly but now for some reason that is not working getting this error message 
![Screen Shot 2022-04-28 at 6 39 03 PM](https://user-images.githubusercontent.com/12478169/165802046-52312ad3-3edb-477c-96d2-26f310d72dd2.png)
Any idea what would it be?

**Comment by yanone** [comment]
Maybe because there are two rlig features in the font?

In the end, Glyphs doesn't matter to us. The fonts need to be built with fontmake. The current font source generates fine with fontmake.

Please finish the work on your sources and either generate them yourself with fontmake for testing purposes, or update the source in the repo and I'll a look.

**Comment by Gue3bara** [comment]
@yanone the current source file on the rep is the latest version 
can you please check it out and let me know if it's working fine with fontmake?

**Comment by yanone** [comment]
Awesome. I'm on the case. Yes, it generates with fontmake.
Since the Slant axis became official in Google Fonts recently, I'm gonna make an update for the normal Cairo as well from the same source. I might have to adjust the Slant axis values as I believe it goes from -1 to 1. (Need to check)

**Comment by yanone** [comment]
No, it's from -90 to +90 (degrees), so you did it right

**Comment by yanone** [comment]
I need to ask you to come up with a new name extension for Cairo Color. Dave forbids "Color" among a few other keywords. He wants the extension to describe the color treatment of the font. For example "Ink" is good for fonts with gradients that mimic calligraphy and ink. "Fun" is good for, well, fun color fonts etc. Hue-related names are also forbidden (Red Lobster).

**Comment by yanone** [comment]
I need to ask you to come up with a new name extension for Cairo Color. Dave forbids "Color" among a few other keywords. He wants the extension to describe the color treatment of the font. For example "Ink" is good for fonts with gradients that mimic calligraphy and ink. "Fun" is good for, well, fun color fonts etc. Hue-related names are also forbidden (Red Lobster).

**Comment by Gue3bara** [comment]
Hello @yanone my apologies for the late reply, i just updated the color version name to "Cairo-PLAY" hopefully that solves the issue

**Comment by yanone** [comment]
Thank you. Play is great. Just take into consideration that you're gonna receive a massive PR back from me, so it's best to not make changes to the repo now or you're gonna have to deal with a lot of data conflicts. Honestly, at this point it's probably best to revert your recent changes immediately and let me make them in my fork instead.

**Comment by Gue3bara** [comment]
Hello @yanone I reverted the change as you requested
