### ISSUE TITLE
Final check for path problems bug?

### ISSUE THREAD

**Issue by Gue3bara** [Gue3bara/Cairo#8]
@davelab6 
as I'm doing a final check on path problems 
I'm getting a result of a problem with path direction for the glyph "multiply" 
<img width="887" alt="screenshot 2016-03-14 06 07 32" src="https://cloud.githubusercontent.com/assets/12478169/13734924/c21f5344-e9ab-11e5-9d06-b6afa869baa6.png">

even though i dont see any issue and when i do "correct path directions" it doesnt do anything because it's on correct direction
<img width="970" alt="screenshot 2016-03-14 06 07 43" src="https://cloud.githubusercontent.com/assets/12478169/13734928/c53d9a22-e9ab-11e5-80d9-5fd742f99f9f.png">

can this be a bug?

**Comment by davelab6** [comment]
> as I'm doing a final check on path problems 

Sorry, remind me again how to do this check?  :)

**Comment by davelab6** [comment]
I checked your Cairo.glyphs file in this repo and I can't see what this issue either. @mekkablue ?

**Comment by Gue3bara** [comment]
@davelab6 it's the script "New tap with path problems" it checks for zero handles and path directions issues 
https://github.com/mekkablue/Glyphs-Scripts/tree/master/Paths

**Comment by davelab6** [comment]
@Gue3bara pretty sure this is a bug. cc @schriftgestalt

**Comment by davelab6** [comment]
I think this glyph is a classic 'remove overlap' challenge, the software can't decide what to do; if you run 'correct directions' the order of the contours is swapped in a cycle

**Comment by schriftgestalt** [comment]
Where does the error message come from?

**Comment by davelab6** [comment]
@schriftgestalt if you apply 'correct directions' to the multiply glyph in the .glyphs file in this repo, it dances the contour order; and if you run @mekkablue 's Paths > New tab with path problems, 

<img width="1500" alt="screen shot 2016-03-14 at 11 03 40" src="https://cloud.githubusercontent.com/assets/261579/13748733/693be8e0-e9d4-11e5-87a4-8ea1b7cc3bab.png">

it outputs

```
Checking for bad paths
Font: Cairo

multiply: found bad path direction on Layer 'Regular'.
multiply: found bad path direction on Layer 'Bold'.
End
```

**Comment by schriftgestalt** [comment]
It is more "Potential Paths problems". So if there is nothing wrong with the path, you can ignore it.

**Comment by davelab6** [comment]
@Gue3bara probably you can close this issue now :)
